# Generated by Django 4.1.2 on 2022-11-15 05:42

from django.db import migrations, models
import django2.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imagem', models.FileField(storage=django2.storage_backends.PublicMediaStorage(), upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
