# Generated by Django 4.1.2 on 2022-11-16 20:43

from django.db import migrations, models
import django2.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_upload_remove_produto_imagem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(default=str, storage=django2.storage_backends.PublicMediaStorage(), upload_to=''),
            preserve_default=False,
        ),
    ]
